// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Proto.Client {
  public static partial class ClientRemoting
  {
    static readonly string __ServiceName = "client.ClientRemoting";

    static readonly grpc::Marshaller<global::Proto.Remote.MessageBatch> __Marshaller_remote_MessageBatch = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Proto.Remote.MessageBatch.Parser.ParseFrom);

    static readonly grpc::Method<global::Proto.Remote.MessageBatch, global::Proto.Remote.MessageBatch> __Method_ConnectClient = new grpc::Method<global::Proto.Remote.MessageBatch, global::Proto.Remote.MessageBatch>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "ConnectClient",
        __Marshaller_remote_MessageBatch,
        __Marshaller_remote_MessageBatch);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Proto.Client.ProtosReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ClientRemoting</summary>
    public abstract partial class ClientRemotingBase
    {
      public virtual global::System.Threading.Tasks.Task ConnectClient(grpc::IAsyncStreamReader<global::Proto.Remote.MessageBatch> requestStream, grpc::IServerStreamWriter<global::Proto.Remote.MessageBatch> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ClientRemoting</summary>
    public partial class ClientRemotingClient : grpc::ClientBase<ClientRemotingClient>
    {
      /// <summary>Creates a new client for ClientRemoting</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ClientRemotingClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ClientRemoting that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ClientRemotingClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ClientRemotingClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ClientRemotingClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::Proto.Remote.MessageBatch, global::Proto.Remote.MessageBatch> ConnectClient(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConnectClient(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Proto.Remote.MessageBatch, global::Proto.Remote.MessageBatch> ConnectClient(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_ConnectClient, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ClientRemotingClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ClientRemotingClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ClientRemotingBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ConnectClient, serviceImpl.ConnectClient).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ClientRemotingBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ConnectClient, serviceImpl.ConnectClient);
    }

  }
}
#endregion
